import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { build } from "vite";

const projectDirectory = process.cwd();
const viewDirectory = path.join(projectDirectory, "src/mcp/recipe-view");
const outputDirectory = path.join(viewDirectory, ".dist");
const generatedModule = path.join(projectDirectory, "src/mcp/generated/recipe-view.ts");

function escapeForInlineScript(source: string) {
  return source.replace(/<\/script/giu, "<\\/script");
}

async function inlineAssets(html: string) {
  for (const match of html.matchAll(/<script([^>]*?)src="([^"]+)"([^>]*)><\/script>/gu)) {
    const source = await readFile(path.join(outputDirectory, match[2].replace(/^\//u, "")), "utf8");
    html = html.replace(
      match[0],
      () => `<script${match[1]}${match[3]}>${escapeForInlineScript(source)}</script>`,
    );
  }
  for (const match of html.matchAll(/<link([^>]*?)href="([^"]+)"([^>]*)>/gu)) {
    const source = await readFile(path.join(outputDirectory, match[2].replace(/^\//u, "")), "utf8");
    html = html.replace(match[0], () => `<style>${source}</style>`);
  }
  return html;
}

async function main() {
  await build({
    root: viewDirectory,
    logLevel: "error",
    build: {
      emptyOutDir: true,
      outDir: outputDirectory,
      assetsInlineLimit: Number.MAX_SAFE_INTEGER,
      cssCodeSplit: false,
      minify: true,
      modulePreload: false,
      rolldownOptions: { output: { codeSplitting: false } },
    },
  });

  const html = await inlineAssets(await readFile(path.join(outputDirectory, "index.html"), "utf8"));
  await mkdir(path.dirname(generatedModule), { recursive: true });
  await writeFile(
    generatedModule,
    [
      "// Generated by scripts/build-mcp-recipe-view.ts. Do not edit by hand.",
      `const recipeViewHtml = ${JSON.stringify(html)};`,
      "",
      "export default recipeViewHtml;",
      "",
    ].join("\n"),
  );
}

void main();
