import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { format } from "oxfmt";
import { build } from "vite";

const projectDirectory = process.cwd();
const views = ["recipe-view", "recipe-search-view"].map((directory) => {
  const viewDirectory = path.join(projectDirectory, "src/mcp", directory);
  return {
    viewDirectory,
    outputDirectory: path.join(viewDirectory, ".dist"),
    generatedModule: path.join(
      projectDirectory,
      "src/mcp/generated",
      directory === "recipe-view" ? "recipe-view.ts" : "search-results.ts",
    ),
    directory,
  };
});

function escapeForInlineScript(source: string) {
  return source.replace(/<\/script/giu, "<\\/script");
}

async function inlineAssets(html: string, outputDirectory: string) {
  for (const match of html.matchAll(/<script([^>]*?)src="([^"]+)"([^>]*)><\/script>/gu)) {
    const source = await readFile(path.join(outputDirectory, match[2].replace(/^\//u, "")), "utf8");
    html = html.replace(
      match[0],
      () => `<script${match[1]}${match[3]}>${escapeForInlineScript(source)}</script>`,
    );
  }
  for (const match of html.matchAll(/<link([^>]*?)href="([^"]+)"([^>]*)>/gu)) {
    const source = await readFile(path.join(outputDirectory, match[2].replace(/^\//u, "")), "utf8");
    html = html.replace(match[0], () => `<style>${source}</style>`);
  }
  return html;
}

async function buildView(view: (typeof views)[number]) {
  await build({
    root: view.viewDirectory,
    logLevel: "error",
    build: {
      emptyOutDir: true,
      outDir: view.outputDirectory,
      assetsInlineLimit: Number.MAX_SAFE_INTEGER,
      cssCodeSplit: false,
      minify: true,
      modulePreload: false,
      rolldownOptions: { output: { codeSplitting: false } },
    },
  });

  const html = await inlineAssets(
    await readFile(path.join(view.outputDirectory, "index.html"), "utf8"),
    view.outputDirectory,
  );
  await mkdir(path.dirname(view.generatedModule), { recursive: true });
  const htmlVariable = view.directory === "recipe-view" ? "recipeViewHtml" : "searchResultsHtml";
  const generatedSource = [
    "// Generated by scripts/build-mcp-recipe-view.ts. Do not edit by hand.",
    `const ${htmlVariable} = ${JSON.stringify(html)};`,
    "",
    `export default ${htmlVariable};`,
    "",
  ].join("\n");
  const formattedSource = await format(view.generatedModule, generatedSource);

  if (formattedSource.errors.some(({ severity }) => severity === "Error")) {
    throw new Error(
      `Failed to format the generated MCP ${view.directory} module: ${formattedSource.errors
        .map(({ message }) => message)
        .join("\n")}`,
    );
  }

  await writeFile(view.generatedModule, formattedSource.code);
}

async function main() {
  for (const view of views) {
    await buildView(view);
  }
}

void main();
